version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./src/maltlager/static:/static
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
  web:
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations maltlager && python manage.py migrate maltlager && python manage.py collectstatic --noinput && gunicorn gysinge.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./src/maltlager/static:/static
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01
